[package]
name = "sheikah_dock"
version = "0.1.0"
authors = ["Lena Voytek"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
package="gtk4"
